version: '3.2'
services:
  app:
    build: .
    entrypoint: npm run debug
    volumes:
      - ./src:/app/src
    depends_on: 
      - mongo
      - mqtt
    ports:
      - "3000:3000"
      - "9229:9229"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
