version: '3'
services:
  app:
    build: .
    depends_on: 
      - mongo
      - mqtt
    ports:
      - "8081:3000"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
