version: '3.2'
services:
  app:
    build: .
    entrypoint: npm run debug
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo
      - mqtt
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - DOCKERIZED=true
      - NODE_ENV=development
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - /data/db
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
