version: '3.2'
services:
  app:
    build: .
    volumes:
      - ./src:/app/src
    depends_on: 
      - mongo
      - mqtt
    ports:
      - "3000:3000"
  mongo:
    image: "mongo"
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
