version: '3'
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  mongo_bootstrap:
    build: ./mongo_bootstrap/
    depends_on:
      - "mongo"
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
